# Generated by Django 3.1.1 on 2020-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scooter',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='name',
            new_name='BikeName',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='type',
            new_name='BrandName',
        ),
        migrations.RemoveField(
            model_name='index',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='index',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='index',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='index',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='index',
            name='offer',
        ),
        migrations.AlterField(
            model_name='index',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
